services:
  - type: web
    name: heart-disease-predictor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5


